---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
    labels:
      expose: "true"
      app: reactor
      version: 1.0-SNAPSHOT
      group: eu.yayi.romdhanisamir
    name: reactor-svc
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: jolokia
      port: 8778
      protocol: TCP
      targetPort: 8778
    - name: prometheus
      port: 9779
      protocol: TCP
      targetPort: 9779
    selector:
      app: reactor
      group: eu.yayi.romdhanisamir
    type: NodePort
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: reactor
      version: 1.0-SNAPSHOT
      group: eu.yayi.romdhanisamir
    name: reactor
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: reactor
        group: eu.yayi.romdhanisamir
    template:
      metadata:
        labels:
          app: reactor
          version: 1.0-SNAPSHOT
          group: eu.yayi.romdhanisamir
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: romdhanisamir/reactor:latest
          imagePullPolicy: Always
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          securityContext:
            privileged: false
